# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5"
])

languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
scheme "DevFest"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

# Delete any screenshots we've previously taken
clear_previous_screenshots true
